# pathways:
#   default: workshop
#
#   paths:
#     workshop:
#       title: "Workshop"
#
#       steps:
#       - 00-workshop-overview
#       - 01-workshop-instructions
#       - 99-workshop-summary
#
#       params:
#       - name: NAME
#         value: undefined
#         aliases:
#         - ALIAS

# modules:
# - name: 00-workshop-overview
#   title: Workshop Overview
# - name: 01-workshop-instructions
#   title: Workshop Instructions
# - name: 99-workshop-summary
#   title: Workshop Summary

# params:
# - name: NAME
#   value: undefined
#   aliases:
#   - ALIAS
