#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/remove
debug:

#@overlay/remove
localKindCluster:
#@overlay/remove
localDNSResolver:

#@overlay/remove
clusterInfrastructure:

#@overlay/remove
imageRegistry:
#@overlay/remove
version:
#@overlay/remove
imageVersions:
#@overlay/remove
clusterRuntime:
#@overlay/remove
clusterIngress:
#@overlay/remove
sessionCookies:
#@overlay/remove
clusterStorage:
#@overlay/remove
clusterSecrets:
#@overlay/remove
clusterSecurity:
#@overlay/remove
workshopSecurity:
#@overlay/remove
trainingPortal:
#@overlay/remove
dockerDaemon:
#@overlay/remove
clusterNetwork:
#@overlay/remove
workshopAnalytics:
#@overlay/remove
websiteStyling:
#@overlay/remove
imagePuller:
#@overlay/remove
lookupService:
