#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def bundle_reference():
#@   registry = data.values.imageRegistry.host
#@   if not registry or registry == "localhost:5001":
#@     registry = "registry.default.svc.cluster.local"
#@   end
#@   if data.values.imageRegistry.namespace:
#@     registry = "{}/{}".format(registry, data.values.imageRegistry.namespace)
#@   end
#@   return "{}/educates-installer:{}".format(registry, data.values.version)
#@ end

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "installer.educates.dev.{}".format(data.values.version)
spec:
  refName: installer.educates.dev
  version: #@ data.values.version
  releasedAt: #@ data.values.releasedAt
  valuesSchema:
    openAPIv3: #@ yaml.decode(data.values.openapi)["components"]["schemas"]["dataValues"]
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: #@ bundle_reference()
      template:
        - ytt:
            paths:
              - "config"
        - kbld:
            paths:
              - ".imgpkg/images.yml"
              - "-"
      deploy:
        - kapp:
            rawOptions:
              - "--app-changes-max-to-keep=5"
