#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

#@ certificate = data.values.ingressSecret.certificate
#@ privateKey = data.values.ingressSecret.privateKey

---
#@ if certificate and privateKey:
apiVersion: v1
kind: Secret
metadata:
  name: #@ "{}-tls".format(data.values.ingressDomain)
  namespace: #@ data.values.namespace
type: kubernetes.io/tls
data:
  tls.crt: #@ base64.encode(data.values.ingressSecret.certificate)
  tls.key: #@ base64.encode(data.values.ingressSecret.privateKey)
#@ end
