#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("educates.lib.yaml", "copy_all_educates_values")

#@overlay/match-child-defaults missing_ok=True
clusterPackages:
  educates:
    #! We only check for educates.enabled here, because we want a
    #! way to disable installing of educates on kind for development purposes.
    enabled: #@ data.values.clusterPackages.educates.enabled
    settings: #@ copy_all_educates_values() if data.values.clusterPackages.educates.enabled else {}
