#@ load("@ytt:data", "data")
#@ load("/00-package.star", "image_reference")

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eduk8s-images
  namespace: #@ data.values.namespace
data:
  PORTAL_IMAGE: #@ image_reference("training-portal")
  BASE_ENVIRONMENT_IMAGE: #@ image_reference("base-environment")
  JDK8_ENVIRONMENT_IMAGE: #@ image_reference("jdk8-environment")
  JDK11_ENVIRONMENT_IMAGE: #@ image_reference("jdk11-environment")
  CONDA_ENVIRONMENT_IMAGE: #@ image_reference("conda-environment")