#@ load("@ytt:data", "data")
#@ load("/00-package.star", "image_reference", "image_pull_policy")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduk8s-operator
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: eduk8s-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: eduk8s-operator
    spec:
      serviceAccountName: eduk8s
      containers:
      - name: eduk8s
        #@ image = image_reference("session-manager")
        image: #@ image
        imagePullPolicy: #@ image_pull_policy(image)
        envFrom:
        - configMapRef:
            name: eduk8s-images
            optional: true
