#@ load("@ytt:data", "data")

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: #@ "secretinjectors.secrets.{}".format(data.values.operatorApiGroup)
  annotations:
    kapp.k14s.io/delete-strategy: orphan
spec:
  scope: Cluster
  group: #@ "secrets.{}".format(data.values.operatorApiGroup)
  names:
    plural: secretinjectors
    singular: secretinjector
    kind: SecretInjector
    categories:
    - #@ "{}-secrets".format(data.values.resourceNamePrefix)
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    required:
                    - sourceSecrets
                    properties:
                      targetNamespaces:
                        type: object
                        properties:
                          nameSelector:
                            type: object
                            required:
                            - matchNames
                            properties:
                              matchNames:
                                type: array
                                items:
                                  type: string
                          uidSelector:
                            type: object
                            required:
                            - matchUIDs
                            properties:
                              matchUIDs:
                                type: array
                                items:
                                  type: string
                          labelSelector:
                            type: object
                            properties:
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                                additionalProperties:
                                  type: string
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  required:
                                  - key
                                  - operator
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                      enum:
                                      - In
                                      - NotIn
                                      - Exists
                                      - DoesNotExist
                                    values:
                                      type: array
                                      items:
                                        type: string
                      sourceSecrets:
                        type: object
                        anyOf:
                        - required:
                          - nameSelector
                        - required:
                          - labelSelector
                        properties:
                          nameSelector:
                            type: object
                            required:
                            - matchNames
                            properties:
                              matchNames:
                                type: array
                                items:
                                  type: string
                          labelSelector:
                            type: object
                            properties:
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                                additionalProperties:
                                  type: string
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  required:
                                  - key
                                  - operator
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                      enum:
                                      - In
                                      - NotIn
                                      - Exists
                                      - DoesNotExist
                                    values:
                                      type: array
                                      items:
                                        type: string
                      serviceAccounts:
                        type: object
                        properties:
                          nameSelector:
                            type: object
                            required:
                            - matchNames
                            properties:
                              matchNames:
                                type: array
                                items:
                                  type: string
                          labelSelector:
                            type: object
                            properties:
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                                additionalProperties:
                                  type: string
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  required:
                                  - key
                                  - operator
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                      enum:
                                      - In
                                      - NotIn
                                      - Exists
                                      - DoesNotExist
                                    values:
                                      type: array
                                      items:
                                        type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
