#@ load("@ytt:data", "data")

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: #@ "secretimporters.secrets.{}".format(data.values.operator.apiGroup)
spec:
  scope: Namespaced
  group: #@ "secrets.{}".format(data.values.operator.apiGroup)
  names:
    plural: secretimporters
    singular: secretimporter
    kind: SecretImporter
    categories:
    - #@ "{}-secrets".format(data.values.operator.namePrefix)
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
          - spec
          properties:
            spec:
              type: object
              properties:
                sourceSecret:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
                sourceNamespaces:
                  type: object
                  properties:
                    nameSelector:
                      type: object
                      required:
                      - matchNames
                      properties:
                        matchNames:
                          type: array
                          items:
                            type: string
                copyAuthorization:
                  type: object
                  required:
                  - sharedSecret
                  properties:
                    sharedSecret:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
