#@ load("@ytt:data", "data")
#@ load("/00-package.star", "image_pull_secrets")

#@ pull_secrets = image_pull_secrets()
#@ if pull_secrets:
---
apiVersion: #@ "secrets.{}/v1beta1".format(data.values.operator.apiGroup)
kind: SecretInjector
metadata:
  name: #@ "{}-image-pull-secrets".format(data.values.operator.namePrefix)
spec:
  rules:
  - targetNamespaces:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operator.apiGroup) @): portal
    sourceSecrets:
      nameSelector:
        matchNames: #@ pull_secrets
    serviceAccounts:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operator.apiGroup) @): portal
  - targetNamespaces:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operator.apiGroup) @): environment
    sourceSecrets:
      nameSelector:
        matchNames: #@ pull_secrets
    serviceAccounts:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operator.apiGroup) @): environment
  - targetNamespaces:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operator.apiGroup) @): environment
    sourceSecrets:
      nameSelector:
        matchNames: #@ pull_secrets
    serviceAccounts:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operator.apiGroup) @): session
#@ end
