#@ load("schema-rules.star", "validate_all")

#@data/values-schema
#@schema/validation ("Error validating config", validate_all)
---
debug: false
#@schema/nullable
clusterPackages:
  #@schema/nullable
  contour:
    enabled: true
    #@schema/nullable
    #@schema/type any=True
    settings: {}
  #@schema/nullable
  cert-manager:
    enabled: false
    #@schema/nullable
    #@schema/type any=True
    settings: {}
  #@schema/nullable
  external-dns:
    enabled: false
    #@schema/nullable
    #@schema/type any=True
    settings: {}
  #@schema/nullable
  certs:
    enabled: false
    #@schema/nullable
    #@schema/type any=True
    settings: {}
  #@schema/nullable
  kyverno:
    enabled: true
    #@schema/nullable
    #@schema/type any=True
    settings: {}
  #@schema/nullable
  kapp-controller:
    enabled: false
    #@schema/nullable
    #@schema/type any=True
    settings: {}
  #@schema/nullable
  educates:
    enabled: true
    #@schema/nullable
    #@schema/type any=True
    settings: {}
#@schema/title "Cluster Infrastructure"
#@schema/desc "Configuration for the cluster infrastructure"
clusterInfrastructure:
  #! NOT IMPLEMENTED: "azure", "gke-autopilot", "minikube"
  #! TODO: Implement validators. e.g. when kind is selected, clusterIngress.domain is required.
  #@schema/validation one_of=["eks", "gke", "kind", "custom", "vcluster", "generic"]
  provider: "custom"
  #@schema/nullable
  #@schema/validation not_null=True, when=lambda _, ctx: ctx.root["clusterInfrastructure"]["provider"] == "eks"
  #@schema/title "AWS specific configuration"
  #@schema/desc "AWS specific configuration to use when provider is set to eks"
  aws:
    #@schema/title "AWS Region"
    #@schema/desc "AWS Region where the cluster exists. This is needed for cert-manager's cluster issuer, when cert-manager is installed"
    #@schema/validation ("region is required for aws based providers",lambda v: len(v) >= 1)
    region: ""
    #@schema/title "Route53 configuration"
    #@schema/desc "Route53 configuration for the AWS account. This will be used by external-dns to manage DNS records"
    #@schema/nullable
    route53:
      #@schema/title "Route53 HostedZone"
      #@schema/desc "Route53 HostedZone to use. When not provided, external-dns will be provided with clusterIngress.domain"
      #@schema/validation ("route53.hostedZone is required for aws based providers",lambda v: len(v) >= 1)
      hostedZone: ""
    #@schema/title "AWS IAM IRSA Roles"
    #@schema/desc "AWS IAM IRSA Roles for external-dns and cert-manager"
    irsaRoles:
      #@schema/example "arn:aws:iam::MY_IAM:role/external-dns" 
      #@schema/validation ("irsaRole for external-dns is required for aws based providers",lambda v: len(v) >= 1)
      external-dns: ""
      #@schema/example "arn:aws:iam::MY_IAM:role/cert-manager"
      #@schema/validation ("irsaRole for cert-manager is required for aws based providers",lambda v: len(v) >= 1)
      cert-manager: ""
  #@schema/nullable
  #@schema/validation not_null=True, when=lambda _, ctx: ctx.root["clusterInfrastructure"]["provider"] == "gcp"
  #@schema/title "GCP specific configuration"
  #@schema/desc "GCP specific configuration to use when provider is set to gke"
  gcp:
    #@schema/title "GCP project"
    #@schema/desc "GCP project where the cluster exists"
    #@schema/validation ("project is required for gcp based providers",lambda v: len(v) >= 1)
    project: ""
    #@schema/title "CloudDNS configuration"
    #@schema/desc "CloudDNS configuration for the GCP project. This will be used by external-dns to manage DNS records"
    #@schema/nullable
    cloudDNS:
      #@schema/title "CloudDNS zone"
      #@schema/desc "CloudDNS zone to use. When not provided, external-dns will be provided with clusterIngress.domain"
      #@schema/validation ("cloudDNS.zone is required for gcp based providers",lambda v: len(v) >= 1)
      zone: ""
    #@schema/title "GCP IAM WorkloadIdentities"
    #@schema/desc "GCP IAM WorkloadIdentities for external-dns and cert-manager"
    workloadIdentity:
      #@schema/example "external-dns@my-project.iam.gserviceaccount.com"
      #@schema/validation ("workloadIdentity for external-dns is required for gcp based providers",lambda v: len(v) >= 1)
      external-dns: ""
      #@schema/example "cert-manager@my-project.iam.gserviceaccount.com"
      #@schema/validation ("workloadIdentity for cert-manager is required for gcp based providers",lambda v: len(v) >= 1)
      cert-manager: ""
  #@schema/title "Additional CA Certificate"
  #@schema/desc "Additional CA Certificates to inject to the cluster. Currently only supported when provider is set to kind"
  #@schema/nullable
  caCertificateRef:
    #@schema/validation min_len=1
    namespace: ""
    #@schema/validation min_len=1
    name: ""
#!--------- educates installation schema
#@schema/nullable
localKindCluster:
  listenAddress: ""
  apiServer:
    address: ""
    port: 6443
  volumeMounts:
    - hostPath: ""
      containerPath: ""
      readOnly: false
#@schema/nullable
localDNSResolver:
  targetAddress: ""
  extraDomains:
    - ""
#!--------- educates training platform schema
#! NOTE: https://github.com/jorgemoralespou/educates-training-platform/blob/develop/carvel-packages/training-platform/bundle/config/00-schema.yaml#L21C1-L33
#! This is only so that the images generates are loaded from this registry. There's a pre-proccesing step that will generate a images file
#! so that this is not needed to be provided by the user.
#@schema/nullable
imageRegistry:
  #@schema/nullable
  #@schema/validation min_len=1
  host: ""
  namespace: ""
#@schema/nullable
version: ""
#@schema/nullable
imageVersions:
  - name: ""
    image: ""
#@schema/nullable
clusterRuntime:
  #@schema/nullable
  class: ""
clusterIngress:
  #@schema/nullable
  domain: ""
  #@schema/nullable
  class: ""
  #@schema/nullable
  protocol: ""
  #@schema/nullable
  tlsCertificate:
    #@schema/validation min_len=1
    tls.crt: ""
    #@schema/validation min_len=1
    tls.key: ""
  #@schema/nullable
  tlsCertificateRef:
    #@schema/validation min_len=1
    namespace: ""
    #@schema/validation min_len=1
    name: ""
  #! This seems to only be needed for provided certificates that are signed by a local CA,
  #! which means that you need to provide the tlsCertificate as well
  #@schema/nullable
  caCertificate:
    #@schema/validation min_len=1
    ca.crt: ""
  #! This seems to only be needed for provided certificates that are signed by a local CA,
  #! which means that you need to provide the tlsCertificate as well
  #@schema/nullable
  caCertificateRef:
    #@schema/validation min_len=1
    namespace: ""
    #@schema/validation min_len=1
    name: ""
  #@schema/nullable
  caNodeInjector:
    enabled: false
#@schema/nullable
sessionCookies:
  domain: ""
#@schema/nullable
clusterStorage:
  #@schema/nullable
  class: ""
  #@schema/nullable
  user: 0
  #@schema/nullable
  group: 1
#@schema/nullable
clusterSecrets:
  pullSecretRefs:
    - namespace: ""
      name: ""
#! This element is not nullable so that kyverno is the default
clusterSecurity:
  #@schema/validation one_of=["pod-security-policies", "pod-security-standards", "security-context-constraints", "kyverno", "none"]
  policyEngine: "kyverno"
#! This element is not nullable so that kyverno is the default
workshopSecurity:
  #@schema/validation one_of=["kyverno", "none"]
  rulesEngine: "kyverno"
#@schema/nullable
trainingPortal:
  #@schema/nullable
  credentials:
    #@schema/nullable
    admin:
      #@schema/validation min_len=1
      username: "educates"
      #@schema/validation min_len=1
      password: ""
    #@schema/nullable
    robot:
      #@schema/validation min_len=1
      username: "robot@educates"
      #@schema/validation min_len=1
      password: ""
  #@schema/nullable
  clients:
    robot:
      #@schema/validation min_len=1
      id: ""
      #@schema/validation min_len=1
      secret: ""
#@schema/nullable
dockerDaemon:
  #@schema/nullable
  networkMTU: 1400
  #@schema/nullable
  proxyCache:
    #@schema/validation min_len=1
    remoteURL: ""
    #@schema/nullable
    username: ""
    #@schema/nullable
    password: ""
#@schema/nullable
clusterNetwork:
  #@schema/default ["169.254.169.254/32", "fd00:ec2::254/128"]
  blockCIDRs:
    - ""
#@schema/nullable
workshopAnalytics:
  #@schema/nullable
  google:
    #@schema/validation min_len=1
    trackingId: ""
  #@schema/nullable
  clarity:
    #@schema/validation min_len=1
    trackingId: ""
  #@schema/nullable
  amplitude:
    #@schema/validation min_len=1
    trackingId: ""
  #@schema/nullable
  webhook:
    #@schema/validation min_len=1
    url: ""
#@schema/nullable
websiteStyling:
  #@schema/nullable
  workshopDashboard:
    #@schema/nullable
    html: ""
    #@schema/nullable
    script: ""
    #@schema/nullable
    style: ""
  #@schema/nullable
  workshopInstructions:
    #@schema/nullable
    html: ""
    #@schema/nullable
    script: ""
    #@schema/nullable
    style: ""
  #@schema/nullable
  workshopStarted:
    html: ""
  #@schema/nullable
  workshopFinished:
    html: ""
  #@schema/nullable
  trainingPortal:
    html: ""
    #@schema/nullable
    script: ""
    #@schema/nullable
    style: ""
  #@schema/nullable
  defaultTheme: ""
  #@schema/nullable
  themeDataRefs:
    - name: ""
      namespace: ""
  #@schema/nullable
  frameAncestors:
    - ""
#@schema/nullable
imagePuller:
  enabled: true
  #@schema/default ["base-environment"]
  prePullImages:
    #@schema/validation min_len=1
    - ""
#@schema/nullable
lookupService:
  enabled: false
  #@schema/nullable
  ingressPrefix: "educates-api"