---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: educateswildcard
spec:
  selfSigned: {}
#! namespace: By default, a ClusterIssuer will create secrets in cert-manager namespace
