#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Secret
metadata:
  name: session-manager-token
  namespace: #@ data.values.operator.namespace
  annotations:
    kubernetes.io/service-account.name: "session-manager"
    kapp.k14s.io/change-rule: #@ "upsert after upserting training.{}/service-accounts".format(data.values.operator.apiGroup)
type: kubernetes.io/service-account-token
