#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:md5", "md5")
#@ load("/00-package.star", "image_reference", "image_pull_policy")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-manager
  namespace: #@ data.values.operator.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: session-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: session-manager
    spec:
      serviceAccountName: session-manager
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: operator
        #@ image = image_reference("session-manager")
        image: #@ image
        imagePullPolicy: #@ image_pull_policy(image)
        volumeMounts:
        - name: config
          mountPath: /opt/app-root/config/
      volumes:
      - name: config
        secret:
          secretName: #@ "{}-config".format(data.values.operator.namePrefix)
